name: Déploiement Docs

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Publier MediaTekDocuments/docs sur gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./MediaTekDocuments/docs
          publish_branch: gh-pages
